INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 1, 35894, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 2, 35898, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 3, 54128, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 4, 35879, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 5, 50558, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 6, 54520, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 7, 43910, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 8, 50220, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 9, 44182, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 10, 3203, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 11, 31109, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 12, 54408, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 13, 49334, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 14, 10495, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 15, 3417, 'CO2; CH4; SF6; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 16, 31185, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 17, 31117, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 18, 1850, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 19, 31052, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 20, 31156, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 21, 35858, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 22, 43912, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 23, 31090, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 24, 31151, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 25, 54329, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 26, 50154, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 27, 35268, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 28, 54113, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 29, 31179, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 30, 35848, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 31, 31112, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 32, 56276, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 33, 50364, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 34, 54354, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 35, 62180, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 36, 54075, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 37, 54048, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 38, 58310, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 39, 50560, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 40, 31166, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 41, 50384, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 42, 31181, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 43, 31165, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 44, 35872, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 45, 35995, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 46, 58628, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 47, 36154, 'CO2; PFCs; CH4; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 48, 35884, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 49, 50673, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 50, 36045, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 51, 31170, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 52, 3422, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 53, 35860, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 54, 46473, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 55, 58489, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 56, 54102, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 57, 54650, 'CO2; CH4; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 58, 14088, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 59, 36254, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 60, 59669, 'CO2; CH4');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 61, 60602, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 62, 16581, 'CO2; CH4; SF6');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 63, 31187, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 64, 31172, 'CO2; CH4; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 65, 8242, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 66, 31146, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 67, 31176, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 68, 31313, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 69, 54443, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 70, 36274, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 71, 55325, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 72, 31446, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 73, 54119, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 74, 35449, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 75, 43928, 'CO2; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 76, 1093, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 77, 36286, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 78, 20113, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 79, 2430, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 80, 31115, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 81, 35886, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 82, 59552, 'CO2; CH4; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 83, 36159, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 84, 50679, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 85, 36262, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 86, 43907, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 87, 58485, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 88, 43920, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 89, 36263, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 90, 35868, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 91, 31155, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 92, 54521, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 93, 46514, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 94, 31111, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 95, 50369, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 96, 49360, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 97, 32550, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 98, 54111, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 99, 31009, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 100, 31110, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 101, 49335, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 102, 42123, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 103, 36495, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 104, 3429, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 105, 55442, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 106, 35859, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 107, 50383, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 108, 35475, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 109, 54104, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 110, 50579, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 111, 50680, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 112, 31114, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 113, 55799, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 114, 31182, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 115, 54070, 'CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 116, 43932, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 117, 50555, 'CO2; CH4');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 118, 55616, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 119, 35393, 'CO2; CH4; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 120, 31173, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 121, 52893, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 122, 54459, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 123, 31169, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 124, 31159, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 125, 54402, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 126, 35902, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 127, 49386, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 128, 32480, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 129, 44132, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 130, 49787, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 131, 35862, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 132, 31175, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 133, 44185, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 134, 54395, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 135, 58609, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 136, 62864, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 137, 10894, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 138, 14874, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 139, 35863, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 140, 54610, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 141, 13067, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 142, 36037, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 143, 54085, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 144, 60656, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 145, 58357, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 146, 35877, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 147, 58627, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 148, 57616, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 149, 54110, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 150, 1184, 'CO2; PFCs; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 151, 58531, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 152, 49338, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 153, 55179, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 154, 59996, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 155, 54337, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 156, 59595, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 157, 50672, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 158, 19233, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 159, 31171, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 160, 58610, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 161, 61753, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 162, 43937, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 163, 54078, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 164, 42120, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 165, 52897, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 166, 54108, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 167, 50578, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 168, 57347, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 169, 59612, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 170, 36518, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 171, 35880, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 172, 61790, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 173, 54529, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 174, 35755, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 175, 31149, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 176, 59165, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 177, 31108, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 178, 31167, 'CO2; CH4');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 179, 54088, 'CO2; CH4');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 180, 42178, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 181, 49363, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 182, 59537, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 183, 54386, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 184, 49342, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 185, 50541, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 186, 54046, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 187, 31164, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 188, 59180, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 189, 54066, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 190, 35274, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 191, 50375, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 192, 35874, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 193, 58513, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 194, 53254, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 195, 35857, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 196, 54389, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 197, 36285, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 198, 31177, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 199, 50568, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 200, 57509, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 201, 69967, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 202, 31163, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 203, 50359, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 204, 58590, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 205, 53959, 'CO2; CH4; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 206, 60318, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 207, 58543, 'CO2; CH4');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 208, 50572, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 209, 54409, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 210, 54388, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 211, 35885, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 212, 31174, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 213, 50382, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 214, 49327, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 215, 63616, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 216, 58461, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 217, 1499, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 218, 59163, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 219, 55324, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 220, 55800, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 221, 60392, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 222, 36036, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 223, 59633, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 224, 50559, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 225, 59160, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 226, 55801, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 227, 60680, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 228, 59631, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 229, 53921, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 230, 59545, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 231, 60419, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 232, 43926, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 233, 58488, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 234, 54461, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 235, 35993, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 236, 62855, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 237, 54356, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 238, 50671, 'CO2');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 239, 58671, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 240, 54497, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 241, 54057, 'CO2; PFCs; CH4; SF6; N2O; NF3; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 242, 55415, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 243, 64014, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 244, 50392, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 245, 54623, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 246, 54092, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 247, 59158, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 248, 54100, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 249, 50650, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 250, 60433, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 251, 58395, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 252, 43911, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 253, 60374, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 254, 63999, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 255, 50371, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 256, 60273, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 257, 35853, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 258, 31154, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 259, 58621, 'CO2; CH4; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 260, 31180, 'CO2; PFCs; CH4; SF6; N2O; HFCs');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 261, 43905, 'CO2; CH4; SF6; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 262, 31113, 'CO2; PFCs; CH4; SF6; N2O; NF3');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 263, 31148, 'CO2; N2O');
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 264, 58796, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 265, 36158, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 266, 54425, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 267, 59151, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 268, 36261, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 269, 50681, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 270, 31055, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 271, 58797, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 272, 58537, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 273, 50211, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 274, 60114, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 275, 55467, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 276, 58636, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 277, 58530, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 278, 14344, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 279, 59535, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 280, 31186, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 281, 44191, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 282, 43934, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 283, 44295, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 284, 51105, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 285, 54390, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 286, 50716, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 287, 36489, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 288, 60603, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 289, 54637, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 290, 60387, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 291, 31150, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 292, 31157, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 293, 54364, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 294, 73295, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 295, 58569, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 296, 73302, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 297, 58511, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 298, 58871, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 299, 51075, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 300, 59563, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 301, 50357, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 302, 36484, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 303, 36252, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 304, 36492, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 305, 60394, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 306, 70247, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 307, 63542, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 308, 43975, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 309, 59167, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 310, 60416, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 311, 60002, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 312, 54347, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 313, 50386, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 314, 58868, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 315, 36426, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 316, 58781, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 317, 60126, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 318, 36002, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 319, 69835, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 320, 840926, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 321, 863190, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 322, 930366, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 323, 60236, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 324, 863463, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 325, 54125, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 326, 850566, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 327, 54365, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 328, 930245, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 329, 60410, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 330, 54607, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 331, 60906, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 332, 50397, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 333, 895694, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 334, 59987, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 335, 54396, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 336, 73746, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 337, 834374, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 338, 840122, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 339, 13506, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 340, 54614, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 341, 852522, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 342, 58668, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 343, 35873, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 344, 60011, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 345, 50373, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 346, 54328, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 347, 930073, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 348, 2621, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 349, 69850, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 350, 54611, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 351, 18078, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 352, 859254, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 353, 848476, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 354, 13113, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 355, 826396, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 356, 54027, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 357, 854055, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 358, 831618, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 359, 54348, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 360, 73723, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 361, 60621, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 362, 11315, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 363, 60599, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 364, 845301, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 365, 14136, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 366, 58595, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 367, 54613, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 368, 54253, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 369, 895157, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 370, 54439, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 371, 60105, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 372, 58597, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 373, 74670, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 374, 859130, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 375, 74325, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 376, 54620, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 377, 36004, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 378, 50678, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 379, 50387, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 380, 15515, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 381, 919095, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 382, 841416, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 383, 847232, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 384, 862953, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 385, 44194, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 386, 54096, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 387, 54289, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 388, 843399, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 389, 44080, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 390, 839668, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 391, 930252, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 392, 840153, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 393, 848564, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 394, 848122, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 395, 863205, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 396, 54706, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 397, 60069, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 398, 866890, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 399, 862501, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 400, 841003, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 401, 827048, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 402, 866940, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 403, 834406, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 404, 50396, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 405, 10806, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 406, 42384, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 407, 60407, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 408, 930367, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 409, 863201, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 410, 54518, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 411, 59532, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 412, 54124, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 413, 917874, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 414, 54318, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 415, 54098, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 416, 60185, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 417, 838939, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 418, 59985, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 419, 54327, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 420, 840514, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 421, 54360, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 422, 862814, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 423, 44210, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 424, 845307, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 425, 848567, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 426, 46470, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 427, 59166, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 428, 54263, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 429, 840269, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 430, 73669, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 431, 59653, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 432, 49389, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 433, 852443, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 434, 68250, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 435, 840075, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 436, 74771, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 437, 43909, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 438, 900978, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 439, 924776, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 440, 60168, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 441, 848259, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 442, 839672, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 443, 849023, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 444, 841960, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 445, 826209, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 446, 35897, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 447, 834157, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 448, 834141, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 449, 54144, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 450, 848981, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 451, 927260, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 452, 848474, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 453, 50361, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 454, 60003, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 455, 68375, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 456, 55379, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 457, 54114, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 458, 859253, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 459, 930371, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 460, 37261, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 461, 59677, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 462, 50370, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 463, 59572, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 464, 863407, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 465, 895653, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 466, 35867, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 467, 73707, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 468, 930254, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 469, 35907, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 470, 834261, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 471, 840131, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 472, 54331, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 473, 929628, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 474, 73667, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 475, 59696, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 476, 73759, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 477, 54361, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 478, 55161, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 479, 834126, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 480, 54330, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 481, 834255, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 482, 54537, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 483, 834161, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 484, 826429, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 485, 849051, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 486, 866486, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 487, 862480, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 488, 826201, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 489, 930332, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 490, 929501, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 491, 54305, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 492, 845302, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 493, 74462, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 494, 59956, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 495, 35893, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 496, 73530, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 497, 54084, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 498, 5871, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 499, 54265, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 500, 827047, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 501, 44180, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 502, 54341, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 503, 863202, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 504, 866903, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 505, 50235, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 506, 50669, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 507, 54349, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 508, 73645, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 509, 54026, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 510, 54513, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 511, 53829, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 512, 73810, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 513, 54290, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 514, 74671, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 515, 49367, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 516, 58613, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 517, 74488, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 518, 15014, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 519, 37241, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 520, 54340, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 521, 848145, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 522, 60625, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 523, 54530, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 524, 930608, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 525, 50358, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 526, 832078, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 527, 74575, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 528, 929630, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 529, 50203, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 530, 73737, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 531, 859128, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 532, 73802, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 533, 54603, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 534, 44299, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 535, 60142, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 536, 73892, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 537, 60078, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 538, 35864, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 539, 60115, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 540, 847236, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 541, 10595, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 542, 68337, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 543, 859179, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 544, 834096, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 545, 840428, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 546, 862932, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 547, 73728, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 548, 73637, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 549, 60384, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 550, 36517, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 551, 918147, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 552, 831234, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 553, 60281, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 554, 73666, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 555, 832610, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 556, 31051, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 557, 54593, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 558, 832300, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 559, 44205, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 560, 60399, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 561, 831620, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 562, 930559, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 563, 852466, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 564, 61467, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 565, 2185, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 566, 852445, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 567, 930269, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 568, 862760, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 569, 42388, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 570, 894137, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 571, 60113, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 572, 31184, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 573, 51374, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 574, 931095, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 575, 60337, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 576, 50394, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 577, 930072, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 578, 840024, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 579, 69849, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 580, 54105, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 581, 826208, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 582, 36032, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 583, 74414, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 584, 31153, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 585, 834144, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 586, 74768, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 587, 840158, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 588, 839666, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 589, 918355, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 590, 73252, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 591, 929561, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 592, 826108, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 593, 841980, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 594, 862705, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 595, 848137, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 596, 54109, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 597, 852480, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 598, 54647, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 599, 57877, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 600, 60640, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 601, 54268, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 602, 44077, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 603, 54519, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 604, 895681, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 605, 863206, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 606, 863470, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 607, 50674, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 608, 60238, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 609, 841269, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 610, 841491, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 611, 54034, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 612, 867237, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 613, 73722, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 614, 63562, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 615, 929500, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 616, 43917, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 617, 50545, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 618, 834284, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 619, 74673, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 620, 862419, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 621, 74463, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 622, 60125, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 623, 63608, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 624, 831431, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 625, 848565, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 626, 826450, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 627, 54419, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 628, 60140, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 629, 862852, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 630, 826211, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 631, 930374, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 632, 54403, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 633, 35856, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 634, 930569, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 635, 895257, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 636, 862482, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 637, 35913, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 638, 841955, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 639, 59657, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 640, 49330, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 641, 54030, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 642, 54699, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 643, 841525, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 644, 834347, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 645, 35865, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 646, 866887, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 647, 826380, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 648, 919724, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 649, 841098, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 650, 54509, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 651, 894047, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 652, 866900, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 653, 74375, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 654, 833284, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 655, 826425, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 656, 852471, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 657, 36223, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 658, 49347, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 659, 49346, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 660, 54277, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 661, 919725, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 662, 841490, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 663, 31158, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 664, 50554, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 665, 54478, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 666, 859097, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 667, 63941, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 668, 73726, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 669, 54617, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 670, 54352, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 671, 863412, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 672, 831952, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 673, 55181, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 674, 895654, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 675, 69968, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 676, 71557, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 677, 50377, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 678, 60226, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 679, 840521, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 680, 60381, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 681, 52896, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 682, 4570, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 683, 73752, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 684, 930413, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 685, 839669, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 686, 831674, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 687, 842012, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 688, 59298, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 689, 73533, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 690, 74594, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 691, 931087, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 692, 929965, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 693, 74418, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 694, 863405, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 695, 850585, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 696, 36218, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 697, 849052, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 698, 54335, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 699, 60393, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 700, 854042, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 701, 840039, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 702, 60102, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 703, 54338, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 704, 50368, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 705, 894138, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 706, 862499, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 707, 60007, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 708, 74481, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 709, 60633, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 710, 60187, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 711, 831999, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 712, 74540, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 713, 834082, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 714, 54308, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 715, 59588, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 716, 73750, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 717, 930134, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 718, 43921, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 719, 859104, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 720, 50380, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 721, 49172, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 722, 73757, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 723, 834382, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 724, 35854, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 725, 862949, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 726, 31054, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 727, 859160, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 728, 826174, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 729, 36410, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 730, 54345, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 731, 73763, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 732, 842044, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 733, 852468, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 734, 44187, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 735, 845304, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 736, 62407, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 737, 862946, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 738, 848125, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 739, 826427, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 740, 826217, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 741, 50562, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 742, 50374, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 743, 848978, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 744, 60400, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 745, 848131, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 746, 863224, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 747, 62171, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 748, 52894, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 749, 60905, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 750, 862520, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 751, 929742, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 752, 930093, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 753, 929627, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 754, 840018, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 755, 69824, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 756, 60216, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 757, 49339, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 758, 55372, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 759, 73742, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 760, 44181, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 761, 832002, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 762, 74672, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 763, 848950, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 764, 863676, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 765, 894051, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 766, 839665, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 767, 860640, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 768, 54488, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 769, 54559, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 770, 863533, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 771, 848970, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 772, 73676, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 773, 59958, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 774, 43908, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 775, 840076, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 776, 866598, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 777, 60108, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 778, 863000, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 779, 73734, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 780, 54116, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 781, 834120, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 782, 840195, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 783, 63762, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 784, 54619, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 785, 60349, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 786, 861779, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 787, 831615, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 788, 74568, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 789, 13490, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 790, 74539, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 791, 847922, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 792, 849041, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 793, 49326, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 794, 831926, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 795, 73413, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 796, 44184, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 797, 73755, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 798, 43938, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 799, 859167, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 800, 36039, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 801, 917936, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 802, 826207, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 803, 60391, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 804, 60104, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 805, 839980, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 806, 60231, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 807, 68290, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 808, 862572, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 809, 831616, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 810, 55371, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 811, 854050, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 812, 59678, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 813, 60018, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 814, 43935, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 815, 826405, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 816, 59538, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 817, 834083, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 818, 73701, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 819, 848977, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 820, 53899, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 821, 930257, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 822, 930007, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 823, 859096, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 824, 863180, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 825, 59708, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 826, 834313, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 827, 73687, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 828, 834373, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 829, 839673, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 830, 31056, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 831, 54339, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 832, 69848, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 833, 35905, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 834, 54370, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 835, 46263, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 836, 54510, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 837, 68267, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 838, 54658, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 839, 73692, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 840, 60638, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 841, 73793, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 842, 74531, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 843, 924935, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 844, 36152, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 845, 53931, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 846, 54060, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 847, 73671, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 848, 54306, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 849, 31178, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 850, 863001, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 851, 924874, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 852, 35870, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 853, 35878, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 854, 35883, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 855, 36477, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 856, 36494, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 857, 43914, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 858, 43930, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 859, 43940, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 860, 50543, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 861, 50551, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 862, 50792, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 863, 54498, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 864, 55334, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 865, 58424, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 866, 60229, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 867, 60577, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 868, 60588, NULL);
INSERT INTO Emissions ( emission_id, Organization_id, gases_included) VALUES ( 869, 63543, NULL);
