INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 1, 'Absolute target', 281);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 2, 'Absolute target', 282);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 3, 'Absolute target', 283);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 4, 'Absolute target', 284);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 5, 'Absolute target', 285);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 6, 'Absolute target', 286);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 7, 'Absolute target', 287);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 8, 'Absolute target', 289);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 9, 'Absolute target', 290);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 10, 'Absolute target', 292);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 11, 'Absolute target', 293);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 12, 'Absolute target', 294);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 13, 'Absolute target', 295);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 14, 'Absolute target', 296);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 15, 'Absolute target', 297);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 16, 'Absolute target', 298);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 17, 'Baseline scenario (business as usual) target', 299);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 18, 'Baseline scenario (business as usual) target', 300);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 19, 'Baseline scenario (business as usual) target', 301);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 20, 'Absolute target', 302);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 21, 'Absolute target', 303);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 22, 'Absolute target', 305);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 23, 'Absolute target', 307);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 24, 'Absolute target', 308);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 25, 'Absolute target', 310);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 26, 'Absolute target', 311);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 27, 'Absolute target', 312);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 28, 'Absolute target', 313);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 29, 'Absolute target', 314);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 30, 'Absolute target', 315);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 31, 'Absolute target', 316);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 32, 'Absolute target', 317);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 33, 'Absolute target', 318);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 34, 'Absolute target', 319);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 35, 'Absolute target', 320);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 36, 'Absolute target', 321);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 37, 'Absolute target', 322);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 38, 'Absolute target', 323);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 39, 'Absolute target', 324);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 40, 'Absolute target', 325);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 41, 'Absolute target', 326);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 42, 'Absolute target', 327);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 43, 'Absolute target', 328);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 44, 'Absolute target', 329);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 45, 'Absolute target', 330);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 46, 'Base year intensity target', 331);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 47, 'Absolute target', 332);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 48, 'Absolute target', 333);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 49, 'Absolute target', 334);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 50, 'Absolute target', 335);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 51, 'Absolute target', 336);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 52, 'Absolute target', 337);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 53, 'Absolute target', 338);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 54, 'Absolute target', 339);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 55, 'Absolute target', 340);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 56, 'Absolute target', 341);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 57, 'Absolute target', 342);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 58, 'Absolute target', 343);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 59, 'Absolute target', 344);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 60, 'Base year intensity target', 345);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 61, 'Absolute target', 346);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 62, 'Absolute target', 347);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 63, 'Baseline scenario (business as usual) target', 348);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 64, 'Absolute target', 349);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 65, 'Absolute target', 351);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 66, 'Absolute target', 352);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 67, 'Absolute target', 353);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 68, 'Absolute target', 354);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 69, 'Absolute target', 355);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 70, 'Baseline scenario (business as usual) target', 356);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 71, 'Baseline scenario (business as usual) target', 357);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 72, 'Baseline scenario (business as usual) target', 358);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 73, 'Baseline scenario (business as usual) target', 359);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 74, 'Baseline scenario (business as usual) target', 360);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 75, 'Baseline scenario (business as usual) target', 361);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 76, 'Absolute target', 362);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 77, 'Absolute target', 363);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 78, 'Absolute target', 364);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 79, 'Absolute target', 366);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 80, 'Absolute target', 367);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 81, 'Absolute target', 368);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 82, 'Absolute target', 369);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 83, 'Absolute target', 371);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 84, 'Absolute target', 372);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 85, 'Absolute target', 373);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 86, 'Absolute target', 374);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 87, 'Baseline scenario (business as usual) target', 375);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 88, 'Absolute target', 376);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 89, 'Absolute target', 377);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 90, 'Absolute target', 378);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 91, 'Absolute target', 379);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 92, 'Absolute target', 380);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 93, 'Absolute target', 383);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 94, 'Absolute target', 384);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 95, 'Baseline scenario (business as usual) target', 385);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 96, 'Absolute target', 386);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 97, 'Absolute target', 387);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 98, 'Base year intensity target', 388);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 99, 'Absolute target', 389);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 100, 'Absolute target', 390);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 101, 'Absolute target', 391);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 102, 'Base year intensity target', 392);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 103, 'Absolute target', 393);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 104, 'Absolute target', 394);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 105, 'Absolute target', 395);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 106, 'Absolute target', 396);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 107, 'Absolute target', 397);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 108, 'Absolute target', 398);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 109, 'Absolute target', 399);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 110, 'Absolute target', 400);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 111, 'Absolute target', 401);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 112, 'Absolute target', 402);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 113, 'Absolute target', 403);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 114, 'Absolute target', 404);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 115, 'Absolute target', 405);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 116, 'Absolute target', 406);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 117, 'Absolute target', 408);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 118, 'Absolute target', 409);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 119, 'Absolute target', 411);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 120, 'Absolute target', 412);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 121, 'Absolute target', 413);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 122, 'Absolute target', 414);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 123, 'Absolute target', 415);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 124, 'Absolute target', 416);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 125, 'Absolute target', 417);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 126, 'Absolute target', 418);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 127, 'Absolute target', 419);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 128, 'Absolute target', 420);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 129, 'Absolute target', 421);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 130, 'Absolute target', 422);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 131, 'Absolute target', 423);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 132, 'Absolute target', 424);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 133, 'Absolute target', 425);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 134, 'Absolute target', 426);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 135, 'Absolute target', 427);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 136, 'Absolute target', 428);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 137, 'Absolute target', 429);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 138, 'Absolute target', 430);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 139, 'Base year intensity target', 431);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 140, 'Absolute target', 432);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 141, 'Absolute target', 433);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 142, 'Absolute target', 434);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 143, 'Absolute target', 435);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 144, 'Absolute target', 436);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 145, 'Absolute target', 437);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 146, 'Absolute target', 438);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 147, 'Absolute target', 439);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 148, 'Absolute target', 440);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 149, 'Absolute target', 441);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 150, 'Absolute target', 442);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 151, 'Absolute target', 443);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 152, 'Absolute target', 444);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 153, 'Absolute target', 445);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 154, 'Absolute target', 446);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 155, 'Absolute target', 447);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 156, 'Absolute target', 448);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 157, 'Absolute target', 449);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 158, 'Absolute target', 450);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 159, 'Absolute target', 452);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 160, 'Absolute target', 453);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 161, 'Absolute target', 454);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 162, 'Absolute target', 455);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 163, 'Absolute target', 456);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 164, 'Absolute target', 457);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 165, 'Absolute target', 458);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 166, 'Absolute target', 459);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 167, 'Absolute target', 460);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 168, 'Absolute target', 461);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 169, 'Absolute target', 462);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 170, 'Absolute target', 463);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 171, 'Absolute target', 464);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 172, 'Absolute target', 466);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 173, 'Absolute target', 467);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 174, 'Absolute target', 468);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 175, 'Absolute target', 469);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 176, 'Absolute target', 470);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 177, 'Absolute target', 471);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 178, 'Absolute target', 472);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 179, 'Absolute target', 473);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 180, 'Absolute target', 474);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 181, 'Absolute target', 475);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 182, 'Absolute target', 477);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 183, 'Absolute target', 478);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 184, 'Absolute target', 479);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 185, 'Absolute target', 480);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 186, 'Absolute target', 482);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 187, 'Baseline scenario (business as usual) target', 483);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 188, 'Absolute target', 484);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 189, 'Absolute target', 485);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 190, 'Absolute target', 486);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 191, 'Absolute target', 488);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 192, 'Absolute target', 489);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 193, 'Absolute target', 490);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 194, 'Absolute target', 491);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 195, 'Absolute target', 492);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 196, 'Absolute target', 493);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 197, 'Absolute target', 494);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 198, 'Absolute target', 495);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 199, 'Base year intensity target', 496);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 200, 'Absolute target', 497);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 201, 'Absolute target', 498);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 202, 'Absolute target', 499);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 203, 'Absolute target', 500);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 204, 'Absolute target', 501);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 205, 'Absolute target', 502);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 206, 'Absolute target', 503);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 207, 'Absolute target', 504);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 208, 'Absolute target', 505);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 209, 'Absolute target', 506);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 210, 'Absolute target', 507);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 211, 'Absolute target', 508);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 212, 'Absolute target', 509);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 213, 'Absolute target', 510);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 214, 'Base year intensity target', 511);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 215, 'Absolute target', 512);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 216, 'Absolute target', 513);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 217, 'Absolute target', 514);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 218, 'Absolute target', 515);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 219, 'Absolute target', 516);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 220, 'Absolute target', 517);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 221, 'Absolute target', 518);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 222, 'Absolute target', 519);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 223, 'Absolute target', 520);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 224, 'Absolute target', 521);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 225, 'Absolute target', 522);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 226, 'Absolute target', 524);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 227, 'Absolute target', 525);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 228, 'Absolute target', 526);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 229, 'Absolute target', 527);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 230, 'Absolute target', 528);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 231, 'Absolute target', 529);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 232, 'Absolute target', 530);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 233, 'Absolute target', 531);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 234, 'Absolute target', 532);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 235, 'Absolute target', 533);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 236, 'Absolute target', 534);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 237, 'Absolute target', 535);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 238, 'Baseline scenario (business as usual) target', 536);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 239, 'Absolute target', 537);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 240, 'Absolute target', 538);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 241, 'Base year intensity target', 539);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 242, 'Absolute target', 540);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 243, 'Absolute target', 541);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 244, 'Absolute target', 542);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 245, 'Absolute target', 543);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 246, 'Absolute target', 544);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 247, 'Baseline scenario (business as usual) target', 545);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 248, 'Baseline scenario (business as usual) target', 546);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 249, 'Baseline scenario (business as usual) target', 547);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 250, 'Baseline scenario (business as usual) target', 548);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 251, 'Baseline scenario (business as usual) target', 549);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 252, 'Baseline scenario (business as usual) target', 550);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 253, 'Baseline scenario (business as usual) target', 551);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 254, 'Baseline scenario (business as usual) target', 552);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 255, 'Absolute target', 553);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 256, 'Absolute target', 554);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 257, 'Absolute target', 555);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 258, 'Absolute target', 556);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 259, 'Absolute target', 557);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 260, 'Absolute target', 558);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 261, 'Absolute target', 559);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 262, 'Absolute target', 560);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 263, 'Absolute target', 561);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 264, 'Absolute target', 562);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 265, 'Absolute target', 563);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 266, 'Absolute target', 564);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 267, 'Absolute target', 565);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 268, 'Absolute target', 566);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 269, 'Absolute target', 567);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 270, 'Absolute target', 568);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 271, 'Absolute target', 570);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 272, 'Base year intensity target', 572);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 273, 'Base year intensity target', 573);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 274, 'Absolute target', 574);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 275, 'Absolute target', 575);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 276, 'Absolute target', 576);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 277, 'Absolute target', 577);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 278, 'Absolute target', 578);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 279, 'Absolute target', 579);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 280, 'Absolute target', 580);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 281, 'Absolute target', 581);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 282, 'Absolute target', 582);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 283, 'Absolute target', 583);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 284, 'Base year intensity target', 584);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 285, 'Baseline scenario (business as usual) target', 585);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 286, 'Absolute target', 586);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 287, 'Absolute target', 587);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 288, 'Absolute target', 588);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 289, 'Absolute target', 589);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 290, 'Baseline scenario (business as usual) target', 591);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 291, 'Absolute target', 592);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 292, 'Absolute target', 593);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 293, 'Absolute target', 594);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 294, 'Absolute target', 595);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 295, 'Baseline scenario (business as usual) target', 598);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 296, 'Baseline scenario (business as usual) target', 599);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 297, 'Baseline scenario (business as usual) target', 600);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 298, 'Base year intensity target', 601);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 299, 'Absolute target', 602);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 300, 'Absolute target', 603);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 301, 'Absolute target', 604);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 302, 'Absolute target', 605);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 303, 'Absolute target', 606);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 304, 'Base year intensity target', 607);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 305, 'Base year intensity target', 608);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 306, 'Base year intensity target', 609);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 307, 'Base year intensity target', 610);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 308, 'Baseline scenario (business as usual) target', 611);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 309, 'Baseline scenario (business as usual) target', 612);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 310, 'Baseline scenario (business as usual) target', 613);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 311, 'Absolute target', 614);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 312, 'Absolute target', 615);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 313, 'Absolute target', 616);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 314, 'Baseline scenario (business as usual) target', 617);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 315, 'Baseline scenario (business as usual) target', 618);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 316, 'Baseline scenario (business as usual) target', 619);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 317, 'Baseline scenario (business as usual) target', 620);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 318, 'Baseline scenario (business as usual) target', 621);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 319, 'Absolute target', 622);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 320, 'Absolute target', 623);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 321, 'Absolute target', 624);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 322, 'Absolute target', 625);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 323, 'Absolute target', 626);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 324, 'Absolute target', 627);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 325, 'Absolute target', 628);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 326, 'Absolute target', 629);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 327, 'Absolute target', 630);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 328, 'Absolute target', 631);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 329, 'Absolute target', 632);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 330, 'Absolute target', 634);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 331, 'Absolute target', 636);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 332, 'Absolute target', 637);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 333, 'Absolute target', 638);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 334, 'Absolute target', 639);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 335, 'Absolute target', 640);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 336, 'Absolute target', 641);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 337, 'Absolute target', 642);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 338, 'Absolute target', 643);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 339, 'Base year intensity target', 644);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 340, 'Absolute target', 645);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 341, 'Absolute target', 646);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 342, 'Absolute target', 647);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 343, 'Absolute target', 648);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 344, 'Absolute target', 649);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 345, 'Absolute target', 650);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 346, 'Absolute target', 651);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 347, 'Absolute target', 652);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 348, 'Absolute target', 653);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 349, 'Absolute target', 654);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 350, 'Absolute target', 655);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 351, 'Absolute target', 656);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 352, 'Absolute target', 658);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 353, 'Absolute target', 659);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 354, 'Absolute target', 661);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 355, 'Absolute target', 662);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 356, 'Absolute target', 663);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 357, 'Absolute target', 664);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 358, 'Absolute target', 665);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 359, 'Absolute target', 666);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 360, 'Absolute target', 667);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 361, 'Absolute target', 668);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 362, 'Absolute target', 669);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 363, 'Absolute target', 672);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 364, 'Absolute target', 673);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 365, 'Absolute target', 674);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 366, 'Base year intensity target', 675);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 367, 'Absolute target', 676);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 368, 'Absolute target', 677);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 369, 'Absolute target', 678);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 370, 'Absolute target', 679);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 371, 'Absolute target', 680);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 372, 'Absolute target', 681);
INSERT INTO Target_Types ( type_of_target_id, type_of_target, target_emission_id) VALUES ( 373, 'Absolute target', 682);
