INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Albania', '(41.153332, 20.168331)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Argentina', '(-38.416097, -63.616672)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Australia', '(-25.274398, 133.775136)', '2', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Belgium', NULL, NULL, '3');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Bolivia', '(-16.290154, -63.588653)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Bosnia & Herzegovina', NULL, NULL, '3');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Brazil', '(-14.235004, -51.92528)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Bulgaria', '(42.697708, 23.321868)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Burundi', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Cameroon', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Canada', '(56.130366, -106.346771)', '3', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Chile', '(-35.675147, -71.542969)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('China', '(35.86166, 104.195397)', '6', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('China, Hong Kong Special Administrative Region', NULL, NULL, '2');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Colombia', '(4.5709, -74.2973)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Comoros', '(-11.6455, 43.3333)', '7', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Costa Rica', NULL, NULL, '1');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Croatia', NULL, NULL, '3');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Cuba', NULL, NULL, '1');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Czechia', NULL, NULL, '3');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Côte d''Ivoire', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Democratic Republic of Congo', '(-4.038333, 21.758664)', '7', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Democratic Republic of the Congo', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Denmark', '(56.26392, 9.501785)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('East Asia', NULL, NULL, '2');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Ecuador', '(-1.831239, -78.183406)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Estonia', '(58.5953, 25.0136)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Eswatini', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Ethiopia', '(9.145, 40.489673)', '7', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Finland', '(61.92411, 25.748151)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('France', '(46.227638, 2.213749)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Georgia', '(40.786168, -81.288192)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Germany', '(51.165691, 10.451526)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Ghana', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Gibraltar', '(36.140751, -5.353585)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Greece', '(39.074208, 21.824312)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Guatemala', NULL, NULL, '1');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Hong Kong', '(22.396428, 114.109497)', '6', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Iceland', '(64.963051, -19.020835)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('India', '(20.5937, 78.9629)', '1', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Indonesia', '(-6.121435, 106.774124)', '2', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Ireland', '(53.41291, -8.24389)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Israel', '(31.046051, 34.851612)', '1', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Italy', '(41.87194, 12.56738)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Japan', '(36.204824, 138.252924)', '6', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Jordan', '(30.585164, 36.238414)', '1', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Kenya', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Latvia', '(56.8796, 24.6032)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Lithuania', '(55.169438, 23.881275)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Madagascar', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Malawi', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Malaysia', '(4.210484, 101.975766)', '2', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Mexico', '(23.634501, -102.552784)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Monaco', '(43.738418, 7.424616)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Montenegro', '(42.708678, 19.37439)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Morocco', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Mozambique', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Namibia', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Netherlands', '(52.132633, 5.291266)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('New Zealand', '(-40.900557, 174.885971)', '2', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Nigeria', '(9.081999, 8.675277)', '7', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Norway', '(60.472024, 8.468946)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Peru', '(-9.19, -75.0152)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Philippines', '(12.879721, 121.774017)', '2', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Poland', '(51.919438, 19.145136)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Portugal', '(39.399872, -8.224454)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Republic of Korea', NULL, NULL, '2');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Romania', '(45.943161, 24.96676)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Russia', '(61.52401, 105.318756)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Senegal', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Sierra Leone', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Singapore', '(1.352083, 103.819836)', '2', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Slovenia', '(46.151241, 14.995463)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('South Africa', '(-30.559482, 22.937506)', '7', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('South Korea', '(35.907757, 127.766922)', '6', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Spain', '(40.463667, -3.74922)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('State of Palestine', '(31.9522, 35.2332)', '1', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Sweden', '(60.128161, 18.643501)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Switzerland', '(46.818188, 8.227512)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Taiwan', '(23.69781, 120.960515)', '6', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Thailand', '(15.870032, 100.992541)', '2', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Togo', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Turkey', '(38.963745, 35.243322)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('USA', '(37.09024, -95.712891)', '3', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Uganda', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('United Arab Emirates', NULL, NULL, '10');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('United Kingdom', '(55.378051, -3.435973)', '5', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('United Kingdom of Great Britain and Northern Ireland', NULL, NULL, '3');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('United Republic of Tanzania', NULL, NULL, '7');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('United States of America', NULL, NULL, '4');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Uruguay', NULL, NULL, '1');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Venezuela', '(6.42375, -66.58973)', '4', NULL);
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Viet Nam', NULL, NULL, '5');
INSERT INTO Countries (country_name, country_location, region_id, cdp_region_id) VALUES ('Vietnam', '(14.058324, 108.277199)', '2', NULL);